INSERT INTO question (questiontext, points, multipleselect, "image") VALUES
('Does the motorcycle driver have to wear a fastened protective helmet while driving?', 2, false, null),
('How long is the registration of a moped valid?', 2, false, null),
('The short light on a bicycle or moped must be designed and adjusted so that the illuminated part of the straight path:', 2, false, null),
('What is the maximum allowed width of the trailer pulled by motorcycles, mopeds, and other two-wheelers?', 2, false, null),
('Is the motorcycle driver required to properly use a protective helmet while riding a motorcycle?', 2, false, null),
('What is the maximum allowed width of a motor vehicle on two and three wheels?', 2, false, null),
('An individual who has passed the driving test and has been issued a driver''s license for category A must not, for two years from the date of issuance, operate a vehicle on a fast road at a speed exceeding:', 2, false, null),
('Can a candidate for category A driving instructor take the practical part of the exam on a motorcycle with an engine capacity of up to 125 cc and engine power of up to 11 kW?', 2, false, null),
('A tricycle is:', 2, false, null),
('If two or more bicycle or moped riders are moving in a group:', 2, false, null),
('If there is a specially designated bicycle lane on the road, a moped rider, if powered by the rider''s power:', 2, false, null),
('On bicycle paths arranged and marked for the traffic of bicycles and mopeds in both directions:', 2, false, null),
('The driver of a bicycle, moped, light motorcycle, and motorcycle must operate the vehicle in a way that does not reduce the stability of the vehicle and does not hinder other traffic participants, especially, they must not:', 2, true, null),
('A driver is:', 2, false, null),
('What is the longitudinal part of the road intended for the traffic of vehicles in one direction with one or more traffic lanes called?', 2, false, null),
('Visibility implies:', 2, false, null),
('A sticker-decal is:', 2, false, null),
('Above the public road, there must be a free space at a height of at least:', 2, false, null),
('What affects the extension of braking distance?', 2, true, null),
('Newly produced motor and trailer vehicles, after mandatory vehicle identification before the first registration, owners are required to undergo regular technical inspection?', 2, false, null),
('What should be avoided when encountering this traffic sign?', 3, true, ARRAY[pg_read_binary_file('/path/in/container/images/a1.png')]),
('How should you act when encountering this traffic sign?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/a2.png')]),
('What danger does this traffic sign warn of?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/a3.png')]),
('How should you proceed when encountering this traffic sign?', 3, true, ARRAY[pg_read_binary_file('/path/in/container/images/a4.png')]),
('The exact name of the traffic sign is?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/a5.png')]),
('The exact name of the traffic sign is:', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/a6.png')]),
('The exact name of the traffic sign is:', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/a7.png')]),
('The exact name of the traffic sign is:', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/a8.png')]),
('How should you act when encountering this traffic sign?', 3, true, ARRAY[pg_read_binary_file('/path/in/container/images/a9.png')]),
('What is the meaning of this traffic sign?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/a10.png')]),
('In the traffic situation depicted in the image, which path must the motorcycle driver take to turn left?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a1i.png')]),
('What is the passing order at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a2i.png')]),
('What is the passing order of vehicles at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a3i.png')]),
('How should the driver of vehicle number 1 act in the traffic situation depicted in the image:', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a4i.png')]),
('What is the passing order of vehicles at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a5i.png')]),
('How should the driver of vehicle number 1 act in the traffic situation depicted in the image?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a6i.png')]),
('What is the passing order of vehicles at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a7i.png')]),
('What is the passing order of vehicles at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a8i.png')]),
('Is it allowed to perform the action of making a U-turn in the traffic situation depicted in the image?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a9i.png')]),
('In the traffic situation depicted in the image, which traffic participant must wait and give way to the other?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a10i.png')]),
('In a residential connecting vehicle (camping trailer), is it allowed to transport passengers?', 2, false, null),
('The driving test for operating a motor vehicle of category B is taken:', 2, false, null),
('What is the maximum allowed width of passenger cars?', 2, false, null),
('How do children usually react in traffic?', 2, false, null),
('How can you contribute to reducing traffic risk with your behavior while driving?', 2, true, null),
('Using a rope, you must not tow:', 2, true, null),
('How long is a medical certificate of fitness for driving a motor vehicle valid?', 2, false, null),
('A rigid connection must not be used to tow a motor vehicle:', 2, false, null),
('Stopping a vehicle is:', 2, false, null),
('A pedestrian is:', 2, false, null),
('How many traffic lanes does a one-way road have?', 2, false, null),
('Alcohol absorption in the blood (alcohol resorption) is completed:', 2, false, null),
('Reduced visibility exists when, due to unfavorable weather or other conditions, a driver cannot clearly see other traffic participants:', 2, false, null),
('Motor vehicles that cannot travel at a speed greater than:', 2, false, null),
('The maximum cross slope of the road for a highway in a tunnel is:', 2, false, null),
('Is it prohibited for a driver to overtake a vehicle approaching a marked pedestrian crossing, or crossing a pedestrian crossing, or stopped to let pedestrians pass at that crossing?', 2, false, null),
('Can a vehicle moving on rails placed in the middle of the road be overtaken on the left side?', 2, false, null),
('What is meant by the term "special object on the road"?', 2, false, null),
('What is meant by the term "vehicle"?', 2, false, null),
('Participants in traffic are obliged to act:', 2, false, null),
('How should you proceed upon encountering this traffic sign?', 3, true, ARRAY[pg_read_binary_file('/path/in/container/images/b1.png')]),
('Which vehicles are prohibited from moving on the road marked by this traffic sign?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/b2.png')]),
('Which vehicles are allowed to move on the road marked by this traffic sign?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/b3.png')]),
('What is the meaning of this traffic sign?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/b4.png')]),
('The exact name of the traffic sign is?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/b5.png')]),
('The exact name of the traffic sign is?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/b6.png')]),
('What is the meaning of the sign given by an authorized person at the intersection?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/b7.png')]),
('Double broken lines are used to mark:', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/b8.png')]),
('When will a driver transporting hazardous materials use this sign?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/b9.png')]),
('How should you proceed upon encountering this traffic sign?', 3, true, ARRAY[pg_read_binary_file('/path/in/container/images/b10.png')]),
('What is the order of vehicle passage at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/b1i.jpg')]),
('What is the order of vehicle passage at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/b2i.jpg')]),
('Which vehicles are not allowed to pass at the intersection in a traffic situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/b3i.jpg')]),
('What is the order of vehicle passage at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/b4i.jpg')]),
('What is the order of vehicle passage at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/b5i.jpg')]),
('What is the order of vehicle passage at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/b6i.jpg')]),
('What is the order of vehicle passage at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/b7i.jpg')]),
('What is the order of vehicle passage at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/b8i.jpg')]),
('What is the order of vehicle passage at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/b9i.jpg')]),
('How must the driver of vehicle number 2 behave in a traffic situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/b10i.jpg')]),
('What is the maximum allowed width of a vehicle with permanent or interchangeable air-conditioned superstructures designed and equipped for the transport of goods in a temperature-controlled environment, whose side walls, including thermal insulation, have a minimum thickness of 45 mm?', 2, false, NULL),
('At what slope must the parking brake of a motor vehicle or trailer, when detached from the towing vehicle, ensure the immobility of the vehicle loaded to the maximum allowed mass, without the vehicle being otherwise braked?', 2, false, NULL),
('At what slope must the parking brake of a vehicle combination ensure the immobility of the entire combination without being braked in another way?', 2, false, NULL),
('Hazardous materials can only be transported by individuals who, among other legally prescribed conditions:', 2, true, NULL),
('Category C includes motor vehicles for transporting cargo whose maximum permissible mass is:', 2, false, NULL),
('Subcategory C1 includes motor vehicles for transporting cargo whose maximum permissible mass is:', 2, false, NULL),
('A candidate for a CE category license can take the driving test if the trailer has a carrying capacity of at least:', 2, false, NULL),
('What is the minimum duration of the driving test for subcategory C1?', 2, false, NULL),
('The maximum allowed mass of a C1E category combination must not exceed:', 2, false, NULL),
('When must a commercial motor vehicle (excluding tractors designed for towing semi-trailers) be marked with a heavy motor vehicle sign?', 2, false, NULL),
('When must trailers be marked with signs for long trailers?', 2, true, NULL),
('Subcategory C1 includes cargo-carrying motor vehicles with a maximum permissible mass not exceeding:', 2, false, NULL),
('On the cargo box of a cargo motor vehicle 9 meters long, railway tracks are continuously supported. The load is properly loaded if:', 2, false, NULL),
('A large goods vehicle is:', 2, false, NULL),
('Must bulk cargo, when transported on a public road, be covered in an appropriate manner to prevent the scattering of the cargo?', 2, false, NULL),
('Signs for marking slow vehicles must be applied to:', 2, false, NULL),
('If you have been issued a C1E subcategory driver''s license, what vehicles are you allowed to drive?', 2, false, NULL),
('The sound signal device installed on motor vehicles falling into the C and C1 driver''s license categories must produce sounds of at least:', 2, false, NULL),
('If a vehicle is transporting cargo in a combination consisting of a towing vehicle and a single-axle trailer, the length of the vehicle is understood to be:', 2, false, NULL),
('What is the maximum allowed speed for cargo motor vehicles towing two trailers?', 2, false, NULL),
('The right to drive a C and CE category motor vehicle is acquired by a person who reaches:', 2, false, NULL),
('The part of the road primarily intended for vehicle traffic is called:', 2, false, NULL),
('While driving a motor vehicle during the day, what lights must be turned on?', 2, false, NULL),
('At intersections and other locations where traffic is regulated by traffic light signals, the "yellow light" illuminated for traffic participants has the following meaning:', 2, false, NULL),
('Can a motor vehicle towing another motor vehicle that cannot move due to a malfunction enter the highway?', 2, false, NULL),
('Which actions endanger traffic safety by the driver?', 2, true, NULL),
('What is the maximum allowed width of a vehicle with permanent or interchangeable air-conditioned superstructures designed and equipped for the transport of goods in a temperature-controlled environment, whose side walls, including thermal insulation, have a minimum thickness of 45 mm?', 2, false, NULL),
('What are the maximum allowed axle loads for individual (drive) axles?', 2, false, NULL),
('If a vehicle transporting children is stopped on the road, on a road with two traffic lanes, while children are getting on or off the vehicle, and you are approaching that vehicle, you must:', 2, false, NULL),
('Reverse driving lights must have such an angle, unless otherwise provided by special permits, that they do not illuminate the road for a length greater than:', 2, false, NULL),
('Exact name of the traffic sign?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/c1.png')]),
('Exact name of the traffic sign?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/c2.png')]),
('What is the meaning of this traffic sign?', 3, true, ARRAY[pg_read_binary_file('/path/in/container/images/c3.png')]),
('What is the meaning of this traffic sign?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/c4.png')]),
('How will you proceed upon encountering this traffic sign?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/c5.png')]),
('How will you proceed upon encountering this traffic sign?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/c6.png')]),
('Which vehicles are allowed to move on roads marked with this traffic sign?', 3, true, ARRAY[pg_read_binary_file('/path/in/container/images/c7.png')]),
('Which vehicles are marked with the sign as shown?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/c8.png')]),
('What is the meaning of this traffic sign?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/c9.png')]),
('How should you act upon encountering this traffic sign?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/c10.png')]),
('What is the order of vehicle passage at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/c1i.png')]),
('What is the order of vehicle passage at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/c2i.png')]),
('What is the order of vehicle passage at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/c3i.png')]),
('What is the order of vehicle passage at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/c4i.png')]),
('What is the order of vehicle passage at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/c5i.png')]),
('What is the order of vehicle passage at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/c6i.png')]),
('What is the order of vehicle passage at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/c7i.png')]),
('What is the order of vehicle passage at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/c8i.png')]),
('How should the driver of vehicle number 2 act in the traffic situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/c9i.png')]),
('How should the driver of vehicle number 2 act in the traffic situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/c10i.png')]),
('What is the total daily driving time for intercity bus management not to exceed?', 2, false, NULL),
('What is the maximum allowed length of a two-axle bus, including detachable parts?', 2, false, NULL),
('In which case must a bus, other than city buses, be equipped with an anti-lock braking system (ABS)?', 2, true, NULL),
('How many candidates for a category D driver''s license can an examiner test in one day?', 2, false, NULL),
('A candidate for a DE category driver''s license can take a driving test if the attached vehicle has:', 2, true, NULL),
('How many first aid kits must a bus with more than 25 seats have?', 2, false, NULL),
('What is the maximum allowed length of a combination of vehicles consisting of a bus and a trailer?', 2, false, NULL),
('As a rule, before starting his working day, a bus driver must have a continuous rest of at least:', 2, false, NULL),
('The speed limit for buses on the highway is restricted to:', 2, false, NULL),
('In the case when a vehicle is not equipped with a tachograph but is used for internal line passenger transport with a total distance of up to 50 km, the driver must have in the vehicle:', 2, true, NULL),
('What is a double crew?', 2, false, NULL),
('The sound signaling device installed in motor vehicles belonging to the D1 and D driver''s license categories must produce sounds of at least:', 2, false, NULL),
('If you have been issued a D1 subcategory driver''s license, what motor vehicles are you entitled to drive?', 2, false, NULL),
('What is the minimum designated free space for one standing place in buses, trolleybuses, and trailer vehicles carrying standing passengers?', 2, false, NULL),
('What is the maximum allowed speed for buses with a passenger-carrying trailer?', 2, false, NULL),
('What is the maximum allowed speed for trolleybuses?', 2, false, NULL),
('What is the maximum allowed speed for city buses?', 2, false, NULL),
('What is the maximum allowed speed for buses that, in addition to built-in seats, have designated standing places?', 2, false, NULL),
('What is the maximum allowed speed for a tourist train?', 2, false, NULL),
('A person can obtain the right to drive a D and DE category motor vehicle at the age of:', 2, false, NULL),
('What is a convoy?', 2, false, NULL),
('What actions must be taken before performing a semi-circular turn?', 2, true, NULL),
('The term "traffic lane" implies:', 2, false, NULL),
('In nighttime conditions, what is the color of the driving indicator on the direction indicator post on the right side in the direction of travel?', 2, false, NULL),
('The "yellow flashing light" traffic light requires all traffic participants to:', 2, false, NULL),
('While driving on a highway, a driver must not:', 2, true, NULL),
('A driver who accumulates at least 10 (ten) penalty points within one year due to violations of the Law on the Basics of Traffic Safety on the Roads in Bosnia and Herzegovina will:', 2, true, NULL),
('A driver who fails to demonstrate the necessary knowledge in the check of traffic regulations may, at his request, undergo the check again:', 2, false, NULL),
('Motor vehicles must be equipped with one or two reverse driving lights on their rear:', 2, false, NULL),
('What is the basic color of danger signs?', 2, false, NULL),
('How should you proceed when encountering this traffic sign?', 3, true, ARRAY[pg_read_binary_file('/path/in/container/images/d1.png')]),
('Which vehicles are not allowed to travel on roads marked with this traffic sign?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/d2.png')]),
('The exact name of the traffic sign is:', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/d3.png')]),
('The exact name of the traffic sign is:', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/d4.png')]),
('What does this traffic sign mean?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/d5.png')]),
('What does this traffic sign prohibit?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/d6.png')]),
('Which vehicles are indicated by markings like those in the picture?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/d7.png')]),
('The exact name of the traffic sign is:', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/d8.png')]),
('What does this traffic sign mean?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/d9.png')]),
('What does this traffic sign mean?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/d10.png')]),
('What is the order of vehicle passage at the intersection in a situation like the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/d1i.jpg')]),
('What is the order of vehicle passage at the intersection in a situation like the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/d2i.jpg')]),
('What is the order of vehicle passage at the intersection in a situation like the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/d3i.jpg')]),
('What is the order of vehicle passage at the intersection in a situation like the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/d4i.jpg')]),
('What is the order of vehicle passage at the intersection in a situation like the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/d5i.jpg')]),
('What is the order of vehicle passage at the intersection in a situation like the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/d6i.jpg')]),
('What is the order of vehicle passage at the intersection in a situation like the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/d7i.jpg')]),
('What is the order of vehicle passage at the intersection in a situation like the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/d8i.jpg')]),
('What is the order of vehicle passage at the intersection in a situation like the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/d9i.jpg')]),
('What is the order of vehicle passage at the intersection in a situation like the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/d10i.jpg')]);