INSERT INTO question (questiontext, points, multipleselect, "image") VALUES
('Does the motorcycle driver have to wear a fastened protective helmet while driving?', 2, false, null),
('How long is the registration of a moped valid?', 2, false, null),
('The short light on a bicycle or moped must be designed and adjusted so that the illuminated part of the straight path:', 2, false, null),
('What is the maximum allowed width of the trailer pulled by motorcycles, mopeds, and other two-wheelers?', 2, false, null),
('Is the motorcycle driver required to properly use a protective helmet while riding a motorcycle?', 2, false, null),
('What is the maximum allowed width of a motor vehicle on two and three wheels?', 2, false, null),
('An individual who has passed the driving test and has been issued a driver''s license for category A must not, for two years from the date of issuance, operate a vehicle on a fast road at a speed exceeding:', 2, false, null),
('Can a candidate for category A driving instructor take the practical part of the exam on a motorcycle with an engine capacity of up to 125 cc and engine power of up to 11 kW?', 2, false, null),
('A tricycle is:', 2, false, null),
('If two or more bicycle or moped riders are moving in a group:', 2, false, null),
('If there is a specially designated bicycle lane on the road, a moped rider, if powered by the rider''s power:', 2, false, null),
('On bicycle paths arranged and marked for the traffic of bicycles and mopeds in both directions:', 2, false, null),
('The driver of a bicycle, moped, light motorcycle, and motorcycle must operate the vehicle in a way that does not reduce the stability of the vehicle and does not hinder other traffic participants, especially, they must not:', 2, true, null),
('A driver is:', 2, false, null),
('What is the longitudinal part of the road intended for the traffic of vehicles in one direction with one or more traffic lanes called?', 2, false, null),
('Visibility implies:', 2, false, null),
('A sticker-decal is:', 2, false, null),
('Above the public road, there must be a free space at a height of at least:', 2, false, null),
('What affects the extension of braking distance?', 2, true, null),
('Newly produced motor and trailer vehicles, after mandatory vehicle identification before the first registration, owners are required to undergo regular technical inspection?', 2, false, null),
('What should be avoided when encountering this traffic sign?', 3, true, ARRAY[pg_read_binary_file('/path/in/container/images/a1.png')]),
('How should you act when encountering this traffic sign?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/a2.png')]),
('What danger does this traffic sign warn of?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/a3.png')]),
('How should you proceed when encountering this traffic sign?', 3, true, ARRAY[pg_read_binary_file('/path/in/container/images/a4.png')]),
('The exact name of the traffic sign is?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/a5.png')]),
('The exact name of the traffic sign is:', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/a6.png')]),
('The exact name of the traffic sign is:', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/a7.png')]),
('The exact name of the traffic sign is:', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/a8.png')]),
('How should you act when encountering this traffic sign?', 3, true, ARRAY[pg_read_binary_file('/path/in/container/images/a9.png')]),
('What is the meaning of this traffic sign?', 3, false, ARRAY[pg_read_binary_file('/path/in/container/images/a10.png')]),
('In the traffic situation depicted in the image, which path must the motorcycle driver take to turn left?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a1i.png')]),
('What is the passing order at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a2i.png')]),
('What is the passing order of vehicles at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a3i.png')]),
('How should the driver of vehicle number 1 act in the traffic situation depicted in the image:', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a4i.png')]),
('What is the passing order of vehicles at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a5i.png')]),
('How should the driver of vehicle number 1 act in the traffic situation depicted in the image?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a6i.png')]),
('What is the passing order of vehicles at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a7i.png')]),
('What is the passing order of vehicles at the intersection in a situation like the one in the picture?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a8i.png')]),
('Is it allowed to perform the action of making a U-turn in the traffic situation depicted in the image?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a9i.png')]),
('In the traffic situation depicted in the image, which traffic participant must wait and give way to the other?', 5, false, ARRAY[pg_read_binary_file('/path/in/container/images/a10i.png')]);