INSERT INTO "option" (questionid, optiontext, iscorrect) VALUES
(1, 'no, they are only required to wear protective goggles', false),
(1, 'yes', true),
(1, 'no', false),
(2, 'not time-limited', true),
(2, 'one year', false),
(2, 'two years', false),
(3, 'is not longer than 35 m nor shorter than 10 m', false),
(3, 'is not longer than 50 m nor shorter than 10 m', true),
(4, '1.00 m', true),
(4, '0.80 m', false),
(5, 'no', false),
(5, 'yes', true),
(6, '1.60 m', false),
(6, '2.00 m', true),
(6, '2.50 m', false),
(7, '60 km/h', false),
(7, '90 km/h', true),
(7, '80 km/h', false),
(8, 'yes', false),
(8, 'no', true),
(9, 'a motor vehicle with three wheels symmetrically arranged about the median longitudinal axis, with a heat engine whose displacement is greater than 50 cm³ or whose maximum design speed is greater than 45 km/h', true),
(9, 'a motor vehicle with three wheels symmetrically arranged about the median longitudinal axis, with a heat engine whose displacement is not greater than 50 cm³ or whose maximum design speed is not greater than 45 km/h', false),
(10, 'they must move one behind the other', true),
(10, 'they are not required to move one behind the other', false),
(11, 'is not required to move on the right bicycle lane in relation to the direction of traffic', false),
(11, 'must move on the right bicycle lane in relation to the direction of traffic', true),
(12, 'vehicles must move on the right side in the direction of vehicle movement', true),
(12, 'vehicles are not required to move on the right side in the direction of vehicle movement', false),
(13, 'release the handlebars, except when signaling a change of direction', true),
(13, 'move as close as possible to the right edge of the roadway', false),
(13, 'remove feet from the pedals', true),
(13, 'move on traffic surfaces where the movement of such vehicles is allowed', false),
(13, 'use headphones for audio devices in both ears', true),
(14, 'any person in traffic on the road who is in a vehicle', false),
(14, 'a person who is driving a vehicle on the road', true),
(15, 'roadway lane', true),
(15, 'roadway', false),
(15, 'traffic lane', false),
(16, 'the space that a participant in road traffic can see from their position', true),
(16, 'the place at an intersection from which the driver can see to the left-right at least 25 m', false),
(16, 'the place at an intersection from which the driver can see to the left at least 25 m', false),
(17, 'proof of a completed technical inspection', false),
(17, 'proof of paid toll', false),
(17, 'proof of vehicle registration', true),
(18, '4.5 m from the highest point of the roadway', true),
(18, '4 m from the highest point of the roadway', false),
(18, '6 m from the highest point of the roadway', false),
(19, 'wet and muddy road', true),
(19, 'dry road', false),
(19, 'vehicle load', true),
(20, 'during the month in which the deadline of 24 months from the day of the first vehicle registration expires, and during the month in which the deadline of 36 months from the day of the first vehicle registration expires', false),
(20, 'during the month in which the deadline of 12 months from the day of the first vehicle registration expires, and during the month in which the deadline of 36 months from the day of the first vehicle registration expires', false),
(20, 'during the month in which the deadline of 24 months from the day of the first vehicle registration expires, and during the month in which the deadline of 48 months from the day of the first vehicle registration expires', true),
(21, 'adjusting driving to the road conditions', false),
(21, 'sudden movements of the steering wheel', true),
(21, 'sudden braking and stopping', true),
(22, 'prepare to navigate through multiple consecutive curves, with the first one turning right', true),
(22, 'warn traffic participants behind you with the right turn indicator', false),
(23, 'proximity to a road section where the roadside is undefined', true),
(23, 'proximity to a road section where the road is frozen', false),
(24, 'continue moving with the vehicle because I have the right of way', false),
(24, 'reduce the speed of the vehicle and, if necessary, stop the vehicle', true),
(24, 'give way to vehicles from the opposite direction', true),
(25, 'prohibition of traffic for all motor vehicles towing a trailer', true),
(25, 'prohibition of traffic for all motor vehicles towing a light trailer', false),
(26, 'electronic toll collection', true),
(26, 'prohibition of using radio devices in the vehicle', false),
(27, 'niche for stopping vehicles in case of danger', true),
(27, 'area reserved for stopping public transport vehicles', false),
(28, 'tire repair workshop', true),
(28, 'place where you can check tire pressure', false),
(29, 'increase attention', true),
(29, 'provide assistance to those injured in a traffic accident', true),
(29, 'increase the speed of the vehicle', false),
(30, 'entering an area where there is an increased risk of uncontrolled fire outbreak', true),
(30, 'entering an area where campfires are allowed for picnickers', false),
(31, 'path number 1', true),
(31, 'path number 2', false),
(32, '1 – 3 – 2', true),
(32, '2 – 3 – 1', false),
(32, '2 – 1 – 3', false),
(33, '2 – 1', false),
(33, '1 – 2', true),
(34, 'give way to vehicle number 3 and then pass before vehicle number 2', true),
(34, 'give way to vehicle number 3, then give way to vehicle number 2, and finally pass through the intersection', false),
(35, '2 – 3 – 4 – 1', false),
(35, '1 – 2 – 3 – 4', false),
(35, '2 – 3 – 1 – 4', true),
(36, 'pass through the intersection before vehicle number 2 and give way to vehicle number 3', false),
(36, 'give way to vehicle number 2 and then pass through the intersection before vehicle number 3', true),
(37, '3 – 4 – 2 – 1', true),
(37, '3 – 1 – 2 – 4', false),
(37, '4 – 2 – 1 – 3', false),
(38, '2 – 1 – 3', false),
(38, '3 – 1 – 2', false),
(38, '2 – 3 – 1', true),
(39, 'yes', true),
(39, 'no', false),
(40, 'number 1', true),
(40, 'number 2', false),
(41, 'yes', false),
(41, 'no', true),
(42, 'on a public road in the city', true),
(42, 'on a test track and on a public road in the city', false),
(42, 'only on a test track', false),
(43, '2.30 m', false),
(43, '2.50 m', true),
(43, '2.70 m', false),
(44, 'reasonably and calmly', false),
(44, 'in accordance with regulations', false),
(44, 'spontaneously and unpredictably', true),
(45, 'aggressive driving', false),
(45, 'adhering to traffic rules and regulations', true),
(45, 'defensive driving', true),
(45, 'nervous driving', false),
(46, 'a motor vehicle with malfunctioning lighting devices', false),
(46, 'a motor vehicle with malfunctioning signaling devices', false),
(46, 'a motor vehicle with malfunctioning braking devices', true),
(46, 'a motor vehicle with malfunctioning steering devices', true),
(46, 'a cargo motor vehicle and a bus', true),
(47, '12 months from the date of issue', true),
(47, '6 months from the date of issue', false),
(48, 'that has a functioning steering device', false),
(48, 'heavier than the towing vehicle if its auxiliary brake is malfunctioning', true),
(49, 'any interruption of the vehicle''s movement on the road lasting up to 15 minutes, except for interruptions made to comply with a sign or rule regulating traffic', false),
(49, 'any interruption of the vehicle''s movement on the road lasting up to 5 minutes, except for interruptions made to comply with a sign or rule regulating traffic', true),
(50, 'a person participating in traffic who does not operate a vehicle, nor is transported in a vehicle or on a vehicle', true),
(50, 'a person operating a vehicle or being transported in a vehicle or on a vehicle', false),
(51, 'two traffic lanes', false),
(51, 'one traffic lane', true),
(51, 'More than two traffic lanes', false),
(52, 'no later than one hour after consumption', true),
(52, 'no later than 24 hours after consumption', false),
(53, 'at least 100 meters outside urban areas, or at least 50 meters in urban areas', false),
(53, 'at least 200 meters on a road outside urban areas, or at least 100 meters in urban areas', true),
(54, '40 km/h', true),
(54, '60 km/h, are not allowed on the highway', false),
(55, '7%', false),
(55, '4%', true),
(56, 'no, if there are two traffic lanes in one direction', false),
(56, 'no, if pedestrians are letting him pass', false),
(56, 'it is prohibited', true),
(57, 'no', true),
(57, 'yes', false),
(58, 'equipment on the road placed to reduce the speed of vehicle movement in places where the safety of traffic participants is particularly endangered', true),
(58, 'protective barriers and toll booths', false),
(59, 'any means of transportation intended for movement on the road, except for motorless wheelchairs for disabled individuals and children''s transportation devices', true),
(59, 'any motor vehicle intended for the transportation of people', false),
(60, 'in accordance with the light traffic sign, provided that the meaning of that sign does not differ from the meaning of other traffic signs or traffic rules', false),
(60, 'in accordance with traffic signals, provided that this does not deviate from the rules of traffic', false),
(60, 'according to signs or orders given by authorized persons even if it deviates from the light traffic sign or other traffic sign or traffic rule', true),
(61, 'reduce the speed of the vehicle and increase attention', true),
(61, 'anticipate the possibility of encountering icy road conditions', true),
(61, 'increase the speed of the vehicle', false),
(62, 'bicycles', false),
(62, 'buses and trucks', true),
(63, 'bicycles, mopeds, and light motorcycles', false),
(63, 'motorcycles', true),
(64, 'prohibition of traffic for vehicles transporting hazardous materials above a certain quantity', false),
(64, 'prohibition of traffic for vehicles transporting explosives or some easily flammable materials', true),
(65, 'area arranged for camping in vehicles', true),
(65, 'prohibited camping in vehicles', false),
(66, 'proximity to a location with a car wash', true),
(66, 'proximity to a location where washing vehicles is prohibited', false),
(67, 'permitted passage for vehicles coming from the sides of the authorized person', false),
(67, 'mandatory stop for all vehicles in front of the intersection', true),
(68, 'traffic lanes with reversible direction of movement regulated by devices giving light traffic signals', true),
(68, 'traffic lanes that can only be used by vehicles with the right of way', false),
(69, 'when transporting at temperatures below 0 °C', false),
(69, 'when transporting hazardous materials at an elevated temperature', true),
(70, 'mandatory turn left', true),
(70, 'continue straight ahead', false),
(71, '5 – 4 – 3 – 2 – 1', true),
(71, '1 – 2 – 3 – 4 – 5', false),
(72, '2 – 3 – 1', false),
(72, '1 – 2 – 3', true),
(72, '3 – 1 – 2', false),
(73, 'vehicle number 4 and number 2', false),
(73, 'vehicle number 1 and number 3', true),
(74, '4 – 3 – 1 – 2', true),
(74, '3 – 4 – 1 – 2', false),
(74, '4 – 3 – 2 – 1', false),
(75, '1 – 2 – 3', false),
(75, '2 – 3 – 1', false),
(75, '3 – 1 – 2', true),
(76, '3 – 1 – 2', true),
(76, '2 – 3 – 1', false),
(76, '1 – 3 – 2', false),
(77, '3 – 2 – 1', true),
(77, '1 – 2 – 3', false),
(77, '2 – 1 – 3', false),
(78, '1 – 3 – 2', false),
(78, '2 – 3 – 1', false),
(78, '2 – 1 – 3', true),
(79, '1 – 3 – 2 – 4', false),
(79, '3 – 1 – 2 – 4', false),
(79, '3 – 2 – 1 – 4', true),
(79, '1 – 4 – 2 – 3', false),
(80, 'pass before vehicle number 1', true),
(80, 'stop and yield to vehicle number 1', false),
(81, '2.55 m', false),
(81, '2.60 m', true),
(81, '2.50 m', false),
(82, '12%', false),
(82, '18%', true),
(83, '6%', false),
(83, '12%', true),
(84, 'have reached 21 years of age', true),
(84, 'have reached 23 years of age', false),
(84, 'have completed professional training for handling and transporting hazardous materials', true),
(85, 'more than 3,500 kg', false),
(85, 'more than 7,500 kg', true),
(86, 'more than 3,500 kg but less than 7,500 kg', true),
(86, 'more than 7,500 kg but less than 12,000 kg', false),
(87, 'minimum 1,000 kg', false),
(87, 'minimum 2,500 kg', true),
(88, 'at least 25 minutes', false),
(88, 'at least 35 minutes', true),
(89, '10,500 kg', false),
(89, '12,000 kg', true),
(90, 'if the maximum permissible mass exceeds 12,000 kg', true),
(90, 'if the maximum permissible mass exceeds 7,500 kg', false),
(90, 'if the maximum permissible mass exceeds 3,500 kg', false),
(91, 'when the length, including the drawbar, exceeds 8 m, and the maximum permissible mass is less than or equal to 10,000 kg', true),
(91, 'when the maximum permissible mass, regardless of the length of the trailer, exceeds 10,000 kg', true),
(91, 'all trailers must carry a sign for long vehicles', false),
(92, '3,500 kg', false),
(92, '5,000 kg', false),
(92, '7,000 kg', false),
(92, '7,500 kg', true),
(93, 'the furthest point at the rear of the vehicle is less than 2 m', false),
(93, 'the furthest point at the rear of the vehicle is less than 1.5 m', true),
(93, 'the furthest point of the load is marked with a square-shaped sign, dimensions 50 x 50 cm, alternating slanting stripes of reflective orange and white colors, positioned vertically on the longitudinal axis of the vehicle', true),
(94, 'a motor vehicle intended and equipped for towing semi-trailers', true),
(94, 'a motor vehicle intended and equipped for towing light trailers', false),
(95, 'yes', true),
(95, 'no', false),
(96, 'motor vehicles and trailers that, for design reasons, cannot travel at speeds greater than 30 km/h on a flat road', true),
(96, 'motor vehicles and trailers that, for design reasons, cannot travel at speeds greater than 40 km/h on a flat road', false),
(96, 'motor vehicles and trailers that, for design reasons, cannot travel at speeds greater than 50 km/h on a flat road', false),
(97, 'combinations of vehicles where the towing vehicles fall into the C1 subcategory, and the trailers have a maximum permissible mass greater than 750 kg, with the condition that the maximum permissible mass of the combination does not exceed 12,000 kg and the maximum permissible mass of the trailer does not exceed the unladen mass of the towing vehicle', true),
(97, 'combinations of vehicles where the towing vehicles fall into category C, and the trailers have a maximum permissible mass greater than 750 kg', false),
(97, 'motor vehicles for transporting cargo with a maximum permissible mass greater than 7,500 kg', false),
(98, '80 dB(A)', true),
(98, '76 dB(A)', false),
(98, '64 dB(A)', false),
(99, 'the length of the towing vehicle', false),
(99, 'the length of the single-axle trailer', false),
(99, 'the total length of the towing vehicle and the single-axle trailer', true),
(100, '70 km/h', false),
(100, '50 km/h', true),
(100, '60 km/h', false),
(101, '18 years of age', false),
(101, '20 years of age', false),
(101, '21 years of age', true),
(102, 'traffic lane', false),
(102, 'roadway', true),
(102, 'traffic lane', false),
(103, 'low or daytime running lights', true),
(103, 'high beams', false),
(103, 'special fog lights', false),
(104, 'obligation for all traffic participants to move particularly cautiously', false),
(104, 'prohibition of passage for all vehicles', false),
(104, 'prohibition of passage, except for vehicles that, at the moment the yellow light appears, are at such a distance from the traffic light that they cannot safely stop before passing it, and for other participants, a prohibition of passage', true),
(105, 'not regulated by the regulations', false),
(105, 'no', true),
(105, 'yes', false),
(106, 'driving while fatigued', true),
(106, 'driving under the influence of alcohol and drugs', true),
(106, 'driving along the right edge of the road', false),
(107, '2.55 m', false),
(107, '2.60 m', true),
(107, '2.50 m', false),
(108, '10 t', false),
(108, '11.5 t', true),
(108, '11 t', false),
(109, 'stop the vehicle while children are getting on and off', true),
(109, 'reduce the speed of the vehicle and continue with particular caution', false),
(109, 'reduce the speed of the vehicle and, if necessary, stop the vehicle', false),
(110, '7.5 m, measured from the light source', false),
(110, '10 m, measured from the light source', true),
(110, '8 m, measured from the light source', false),
(111, 'intersection of equal importance roads', false),
(111, 'crossing of side roads at a sharp angle', true),
(112, 'drawbridge', true),
(112, 'proximity to the shore', false),
(113, 'prohibition of traffic in both directions', false),
(113, 'prohibition of traffic in the direction of vehicle movement', true),
(113, 'Traffic is allowed from the opposite direction', true),
(114, 'Extension of the road with the right of way', false),
(114, 'End of the road or part of the road with the right of way', true),
(115, 'continue moving with increased attention because I have the right of way compared to vehicles coming from the opposite direction', true),
(115, 'stop the vehicle and let vehicles from the opposite direction pass', false),
(116, 'reduce the speed of the vehicle to the speed of pedestrian movement', true),
(116, 'increase the speed of the vehicle', false),
(117, 'bicycle', false),
(117, 'passenger car, truck, bus', true),
(117, 'motorcycle', true),
(118, 'vehicles transporting hazardous materials', false),
(118, 'slow vehicles', true),
(119, 'danger for which no specific sign is provided', true),
(119, 'danger when driving on a slippery road', false),
(120, 'downshift in a timely manner', true),
(120, 'shift to a higher gear and brake as much as possible with the foot brake', false),
(121, '3 – 1 – 2', true),
(121, '2 – 1 – 3', false),
(121, '1 – 2 – 3', false),
(122, '1 – 2 – 3', false),
(122, '3 – 1 – 2', false),
(122, '1 – 3 – 2', true),
(123, '1 – 3 – 2', true),
(123, '2 – 1 – 3', false),
(123, '3 – 2 – 1', false),
(124, '3 – 2 – 1', false),
(124, '1 – 3 – 2', true),
(124, '1 – 2 – 3', false),
(125, '1 – 2 – 3', true),
(125, '2 – 1 – 3', false),
(125, '3 – 1 – 2', false),
(126, '1 – 2 – 3', false),
(126, '2 – 1 – 3', false),
(126, '3 – 1 – 2', true),
(127, '3 – 2 – 1', false),
(127, '2 – 1 – 3', false),
(127, '1 – 3 – 2', true),
(128, '1 – 2 – 3', false),
(128, '2 – 1 – 3', false),
(128, '3 – 1 – 2', true),
(129, '3 – 2 – 1', false),
(129, '2 – 1 – 3', false),
(129, '1 – 3 – 2', true),
(130, 'pass before vehicle number 1', true),
(130, 'yield to vehicle number 1', false),
(131, '4.5 h', false),
(131, '7 h', false),
(131, '9 h', true),
(132, '13.50 m', true),
(132, '15.00 m', false),
(133, 'if its maximum permissible weight exceeds 12 t', true),
(133, 'if it was produced after January 1, 1994', true),
(133, 'if its maximum permissible weight exceeds 9 t', false),
(134, '6 candidates', true),
(134, '8 candidates', false),
(135, 'a maximum permissible weight greater than 750 kg', true),
(135, 'a closed cargo space, at least 3 m wide and 3 m high', false),
(135, 'a closed cargo space, at least 2 m wide and 2 m high', true),
(136, 'one kit', false),
(136, 'two kits', true),
(136, 'three kits', false),
(137, '16.50 m', false),
(137, '17.50 m', false),
(137, '18.75 m', true),
(137, '20.00 m', false),
(138, '10 h', false),
(138, '8 h', false),
(138, '11 h', true),
(139, '75 km/h', false),
(139, '80 km/h', false),
(139, '90 km/h', false),
(139, '100 km/h', true),
(140, 'a duty schedule and a copy of the timetable', true),
(140, 'duty schedule only', false),
(141, 'a crew consisting of four drivers', false),
(141, 'a crew consisting of two drivers', true),
(142, '90 dB(A)', false),
(142, '93 dB(A)', true),
(143, 'motor vehicles for transporting passengers with more than eight but no more than sixteen seats', true),
(143, 'motor vehicles for transporting cargo with a maximum permissible weight greater than 3,500 kg and less than 7,500 kg', false),
(143, 'motor vehicles for transporting cargo with a maximum permissible weight greater than 7,500 kg', false),
(144, '0.15 m², and for city buses 0.125 m²', true),
(144, '0.18 m²', false),
(144, '0.20 m²', false),
(145, '70 km/h', false),
(145, '50 km/h', true),
(145, '60 km/h', false),
(146, '50 km/h', true),
(146, '70 km/h', false),
(146, '60 km/h', false),
(147, '70 km/h', false),
(147, '60 km/h', false),
(147, '50 km/h', true),
(148, '70 km/h', false),
(148, '50 km/h', true),
(148, '60 km/h', false),
(149, '30 km/h', false),
(149, '20 km/h', true),
(149, '40 km/h', false),
(150, '21', false),
(150, '24', true),
(151, 'a sequence of at least three vehicles stopped on the road or moving in close proximity in the same traffic lane in the same direction, where the speed and actions of the drivers are mutually conditioned, and between which, without hindrance, no other vehicle can enter', true),
(151, 'a sequence of at least five vehicles stopped on the road or moving in close proximity in the same traffic lane in the same direction, where the speed and actions of the drivers are mutually conditioned, and between which, without hindrance, no other vehicle can enter', false),
(152, 'make sure that the maneuver can be done without endangering other traffic participants or property', true),
(152, 'activate the simultaneous flashing of all direction indicators', false),
(152, 'pay attention to the vehicle''s position, direction, and speed', true),
(153, 'the longitudinal part of the roadway intended for the traffic of motor vehicles', false),
(153, 'a marked or unmarked longitudinal part of the roadway whose width is sufficient for the unobstructed traffic of a single row of vehicles', true),
(154, 'red on the right side and black on the left side', false),
(154, 'red on the right side and white on the left side', true),
(154, 'black on the right side and white on the left side', false),
(155, 'prepare for a red light', false),
(155, 'prepare for a green light', false),
(155, 'proceed with special caution, and the light signaling device is not in traffic control function', true),
(156, 'change the lane he was previously in', false),
(156, 'move the vehicle backward', true),
(156, 'perform a semi-circular turn', true),
(157, 'have the driver''s license revoked for 60 days', false),
(157, 'have the driver''s license revoked for 30 days', true),
(157, 'be sent for a check of knowledge of traffic regulations', true),
(158, 'after 15 days from the date of the previous check', true),
(158, 'after 30 days from the date of the previous check', false),
(159, 'white', true),
(159, 'red or yellow', false),
(160, 'yellow, with red edges on the triangle, except for signs I-25 (roadworks) and I-43 (traffic accident), whose basic color is yellow', false),
(160, 'blue, with symbols and inscriptions in white', false),
(160, 'white, with red edges on the triangle, except for signs I-25 (roadworks) and I-43 (traffic accident), whose basic color is yellow', true),
(161, 'reduce the speed of the vehicle', true),
(161, 'increase attention and expect cyclists', true),
(161, 'increase the speed of the vehicle', false),
(162, 'vehicles with axle load greater than specified on the sign', true),
(162, 'vehicles with axle load less than specified on the sign', false),
(163, 'prohibition of traffic for all motor vehicles, except motorcycles without trailers and mopeds', true),
(163, 'prohibition of traffic for all motor vehicles, except motorcycles without trailers', false),
(164, 'prohibition of traffic for bicycles', true),
(164, 'prohibition of traffic for bicycles and mopeds', false),
(165, 'mandatory overtaking on the left side', true),
(165, 'mandatory direction', false),
(166, 'stopping the vehicle', false),
(166, 'parking the vehicle', true),
(167, 'heavy vehicles', true),
(167, 'vehicles wider than 2.5 m', false),
(168, 'right of way for vehicles from the opposite direction', false),
(168, 'permitted direction', false),
(168, 'two-way traffic', true),
(169, 'possible irregularities and protrusions on the road', false),
(169, 'danger of falling rocks on the road', true),
(170, 'proximity to a level crossing over a railway without barriers or half-barriers', false),
(170, 'proximity to a level crossing over a railway with barriers or half-barrier', true),
(170, 'approaching a wooden bridge', false),
(171, '3 – 1 – 2', false),
(171, '3 – 2 – 1', false),
(171, '2 – 1 – 3', true),
(172, '1 – 2 – 3 – 4', true),
(172, '4 – 1 – 2 – 3', false),
(172, '2 – 3 – 4 – 1', false),
(173, '2 – 1 – 3', false),
(173, '3 – 1 – 2', true),
(173, '1 – 2 – 3', false),
(174, '3 – 2 – 1', false),
(174, '1 – 2 – 3', true),
(174, '2 – 1 – 3', false),
(175, '2 – 3 – 1', true),
(175, '1 – 3 – 2', false),
(175, '3 – 2 – 1', false),
(176, '2 – 3 – 1', false),
(176, '3 – 1 – 2', false),
(176, '3 – 2 – 1', true),
(177, '1 – 2 – 3', false),
(177, '2 – 1 – 3', false),
(177, '3 – 2 – 1', true),
(178, '2 – 3 – 1', true),
(178, '3 – 2 – 1', false),
(178, '1 – 2 – 3', false),
(179, '2 – 3 – 1', false),
(179, '1 – 3 – 2', true),
(179, '1 – 2 – 3', false),
(180, '3 – 2 – 1', false),
(180, '3 – 1 – 2', true),
(180, '1 – 2 – 3', false),
(181, 'from the left traffic lane', true),
(181, 'from the right traffic lane', false),
(182, 'blue rotating light', false),
(182, 'yellow rotating light', true),
(183, 'at least one light emitting white light', true),
(183, 'at least two lights emitting yellow light', false),
(184, '20 km/h', true),
(184, '30 km/h', false),
(184, '40 km/h', false),
(185, 'the driver can easily, quickly, and safely change the direction and direction of vehicle movement', true),
(185, 'the front wheels of the vehicle, when moving on a horizontal flat surface, after releasing the steering wheel, return to the position for straight-line movement', true),
(185, 'it allows the free movement of the steering wheel on the vehicle greater than 30°', false),
(186, 'give them a deadline to undergo testing or examination', false),
(186, 'temporarily confiscate the driver''s license on the spot', true),
(186, 'exclude the vehicle from traffic', false),
(187, '25 km/h', true),
(187, '30 km/h', false),
(188, '25 km/h', false),
(188, '30 km/h', true),
(188, '40 km/h', false),
(189, 'only about drivers', false),
(189, 'only about vehicles', false),
(189, 'about all drivers and vehicles', true),
(190, '1 mm', false),
(190, '1.6 mm', true),
(190, '2 mm', false),
(191, 'park the vehicle', true),
(191, 'stop the vehicle', false),
(192, 'no', true),
(192, 'yes', false),
(193, 'overtaking', false),
(193, 'passing', true),
(194, 'the final and enforceable misdemeanor order or final court decision', true),
(194, 'the Ministry of Interior''s decision where the driver is recorded', false),
(195, '0.0 g/kg', true),
(195, '0.3 g/kg', false),
(195, '0.5 g/kg', false),
(196, 'the total weight of the vehicle', false),
(196, 'the weight of the vehicle together with its payload', true),
(197, 'is not heavier or longer than the towing vehicle', false),
(197, 'falls into the same category as the towing vehicle', false),
(197, 'does not significantly reduce the stability of the towing vehicle', true),
(198, 'more than 50 m away', false),
(198, 'more than 100 m away', true),
(199, 'a maximum of 6 months and can be extended for a maximum of another 6 months for justified reasons', false),
(199, 'a maximum of one year and can be extended for a maximum of another year for justified reasons', true),
(200, 'the internal affairs authority or the organization entrusted with moving the vehicle', false),
(200, 'the owner or driver of the vehicle', true),
(201, 'no entry for vehicles transporting dangerous substances', true),
(201, 'no entry for cargo vehicles transporting dangerous substances', false),
(202, 'no entry for vehicles exceeding a specified two-axle load', true),
(202, 'no entry for vehicles whose load per single axle exceeds the load marked on the sign', false),
(203, 'pedestrian path', true),
(203, 'zone of calm traffic', false),
(204, 'one-way road', false),
(204, 'mandatory direction', true),
(205, 'long vehicles', true),
(205, 'vehicles whose width exceeds 2.5 m', false),
(206, 'possible skidding and running off the road', true),
(206, 'increased control while driving a vehicle', false),
(206, 'possible damage or breakage of vehicle parts', true),
(207, 'movable bridge', false),
(207, 'proximity to the shore', true),
(208, 'animals on the road', true),
(208, 'game on the road', false),
(209, 'no overtaking for all motor vehicles, except motorcycles without trailers and mopeds', true),
(209, 'no overtaking for all motor vehicles, except mopeds', false),
(210, 'vehicles whose total height exceeds the height marked on the sign', true),
(210, 'vehicles whose total height does not exceed the height marked on the sign', false),
(211, '1 – 3 – 2', true),
(211, '2 – 3 – 1', false),
(211, '2 – 1 – 3', false),
(212, '3 – 2 – 1', false),
(212, '3 – 1 – 2', true),
(212, '1 – 2 – 3', false),
(213, '1 – 2 – 3', false),
(213, '2 – 1 – 3', true),
(213, '3 – 1 – 2', false),
(214, '3 – 2 – 1', true),
(214, '2 – 1 – 3', false),
(214, '1 – 2 – 3', false),
(215, '3 – 2 – 1', true),
(215, '2 – 1 – 3', false),
(215, '1 – 3 – 2', false),
(216, '2 – 1 – 3', false),
(216, '1 – 3 – 2', true),
(216, '3 – 1 – 2', false),
(217, '3 – 2 – 1', false),
(217, '1 – 3 – 2', false),
(217, '2 – 1 – 3', true),
(218, '2 – 3 – 1', true),
(218, '1 – 2 – 3', false),
(218, '3 – 2 – 1', false),
(219, '2 – 1 – 3 – 4', false),
(219, '1 – 2 – 3 – 4', true),
(219, '1 – 2 – 4 – 3', false),
(220, '2 – 3 – 1', true),
(220, '1 – 3 – 2', false),
(220, '3 – 2 – 1', false),
(221, 'exact location, number of injured persons, and type of injuries', true),
(221, 'exact location, number of injured persons regardless of the degree of injury', false),
(221, 'exact location without describing injuries', false),
(222, 'condition accompanied by choking', false),
(222, 'head injury accompanied by unconsciousness', false),
(222, 'spinal injury', true),
(223, 'medical personnel immediately called', false),
(223, 'a passerby or someone at the scene', true),
(223, 'specialized on-site services', false),
(224, 'visible blood on clothing, deep breathing, weakness', false),
(224, 'slow pulse and high blood pressure, weakness, restlessness', false),
(224, 'extreme paleness, rapid and shallow breathing (shortness of breath), difficult-to-feel and rapid pulse, skin moistened with cold sweat, thirst, general weakness, lethargy', true),
(225, 'cessation of breathing, unconsciousness, and severe bleeding', true),
(225, 'blow to the head with a blunt object', false),
(225, 'fracture of the spinal column', false),
(226, 'sudden stressful situation', false),
(226, 'a serious condition caused by loss of blood, fluids, and intense pain', true),
(226, 'fear of the consequences of an accident', false),
(227, 'placing the injured body part in an immovable, stable position, out of function for a certain period', true),
(227, 'putting the body in a state of readiness and urgent transport', false),
(227, 'placing the injured person on their stomach and urgent transport', false),
(228, 'immobilize one injured joint', false),
(228, 'immobilize two adjacent joints', false),
(228, 'immobilize all joints', true),
(229, '20 minutes', false),
(229, '40 minutes', false),
(229, 'until professional help arrives', true),
(230, 'if more than 10 minutes have safely passed since cardiac arrest', true),
(230, 'if there is an open wound on the chest', false),
(230, 'if the burned surface of the body is larger than 60%', false);