version: '3'
services:
  postgres:
    container_name: eDrivingSchool
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: eDrivingSchoolDB
    ports:
      - "5432:5432"
    volumes:
      - my_data:/var/lib/postgresql/data
      - ./images:/path/in/container/images
volumes:
  my_data: