version: '3'
services:
  postgres:
    container_name: praksa
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: admin
      POSTGRES_DB: dlts
    ports:
      - "5432:5432"
    volumes:
      - my_data:/var/lib/postgresql/data
volumes:
  my_data: